# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  branches:
    include:
      - master
pr:
  - master

pool:
  vmImage: 'macos-latest'

variables:
- group: sampleapp-keystore

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: '$(Build.Repository.LocalPath)/gradlew'
    workingDirectory: '$(Build.Repository.LocalPath)'
    tasks: 'clean build test assembleRelease'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo 'Hello world'
      ls $(Build.ArtifactStagingDirectory)
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'appcenter-sampleapp.keystore'
- task: AndroidSigning@3
  inputs:
    apkFiles: '$(Build.SourcesDirectory)/app/build/outputs/apk/release/*.apk'
    apksignerKeystoreFile: 'appcenter-sampleapp.keystore'
    apksignerKeystorePassword: '$(keystore-password)'
    apksignerKeystoreAlias: '$(android-alias)'
    apksignerKeyPassword: '$(android-key-password)'
- task: AppCenterTest@1
  inputs:
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
    frameworkOption: 'appium'
    credentialsOption: 'serviceEndpoint'
    localeOption: 'en_US'